# Generated by Django 5.0.3 on 2024-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_age_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='small_description',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Краткое описание'),
        ),
    ]
