# Generated by Django 5.0.3 on 2024-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('people', models.IntegerField(default=0)),
                ('days', models.DateTimeField()),
                ('description', models.TextField()),
                ('travel_now', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('MAN', 'МУЖЧИНА'), ('WOMAN', 'ЖЕНЩИНА')], default='MAN', max_length=5)),
                ('search_travel', models.CharField(choices=[('SF', 'СЕМЬЮ'), ('SW', 'ЖЕНЩИНУ'), ('SM', 'МУЖЧИНУ')], default='SF', max_length=13)),
                ('country', models.ManyToManyField(related_name='travels', to='travels.country')),
            ],
            options={
                'verbose_name': 'Путешествия',
            },
        ),
    ]
