# Generated by Django 5.0.3 on 2024-03-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='people',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город, Курорт'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='days',
            field=models.DateField(verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.TextField(verbose_name='Описание путешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_now',
            field=models.BooleanField(default=False, verbose_name='Уже путешествую'),
        ),
    ]
