# Generated by Django 5.0.3 on 2024-03-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_remove_travel_people_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город, Курорт'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, related_name='travels', to='travels.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание путешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAN', 'МУЖЧИНА'), ('WOMAN', 'ЖЕНЩИНА')], default='MAN', max_length=5, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='search_travel',
            field=models.CharField(blank=True, choices=[('SF', 'СЕМЬЮ'), ('SW', 'ЖЕНЩИНУ'), ('SM', 'МУЖЧИНУ')], default='SF', max_length=13, null=True, verbose_name='Кого ищет'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_now',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Уже путешествую'),
        ),
    ]
