# Generated by Django 5.0.3 on 2024-03-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_travel_date_alter_travel_city_alter_travel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна'),
        ),
    ]
