# Generated by Django 5.0.3 on 2024-03-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_travel_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={},
        ),
        migrations.RemoveField(
            model_name='travel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='search_travel',
        ),
    ]
