# Generated by Django 5.0.3 on 2024-03-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_alter_travel_options_remove_travel_author_and_more'),
        ('users', '0005_city_customuser_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Путешествие', 'verbose_name_plural': 'Путешествия'},
        ),
        migrations.AddField(
            model_name='travel',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
    ]
